services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 2
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9093
      - --memory 4G
    ports:
      - "9093:9093"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./config/database:/config/database
    environment:
      - CASSANDRA_CLUSTER_NAME=market_data_cluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=datacenter1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-init:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./config/database:/config/database
    command: /bin/bash -c "cqlsh cassandra -f /config/database/cassandra_schema_dev.cql"
    networks:
      - kafka-network
    restart: on-failure

  # Single Spark dev container with all components
  spark:
    image: bitnami/spark:latest
    ports:
      - "8090:8080"  # Spark UI
      - "7077:7077"  # Spark master port
      - "4040:4040"  # Application UI
    volumes:
      - ./src:/opt/bitnami/spark/src
      - ./config:/opt/bitnami/spark/config
      - ./scripts:/opt/bitnami/spark/scripts
      - spark-volume:/bitnami
    environment:
      - SPARK_MODE=master
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
      - MARKET_DATA_TOPIC=market_data
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - kafka-network
    depends_on:
      - redpanda
      - cassandra
    command: >
      bash -c "
        echo 'Setting up development environment...' &&
        pip install pyspark kafka-python cassandra-driver pandas matplotlib jupyter yfinance &&
        mkdir -p /tmp/checkpoints &&
        chmod 777 /tmp/checkpoints &&
        echo 'Spark development environment ready!' &&
        echo 'Run your script manually with:' &&
        echo '/opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0,com.datastax.spark:spark-cassandra-connector_2.12:3.3.0 /opt/bitnami/spark/src/data_processing/market_data/feature_eng/stock_features.py' &&
        tail -f /dev/null
      "


  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda
    networks:
      - kafka-network

volumes:
  redpanda-data:
  spark-volume:
  cassandra-data:

networks:
  kafka-network:
    driver: bridge