services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 2
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9093
      - --memory 4G
    ports:
      - "9093:9093"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./config/mongodb:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb_user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_password
      - MONGO_INITDB_DATABASE=social_media
    networks:
      - kafka-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 15s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Single Spark dev container with all components
  spark:
    image: bitnami/spark:latest
    ports:
      - "8090:8080"  # Spark UI
      - "7077:7077"  # Spark master port
      - "4040:4040"  # Application UI
    volumes:
      - ./src:/opt/bitnami/spark/src
      - ./config:/opt/bitnami/spark/config
      - ./scripts:/opt/bitnami/spark/scripts
      - ./logs/spark:/opt/bitnami/spark/logs
      - spark-volume:/bitnami
    environment:
      - SPARK_MODE=master
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - kafka-network
    depends_on:
      - redpanda
      - mongodb
    command: >
      bash -c "
        echo 'Setting up development environment...' &&
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir \"yfinance>=0.2.54,<1.0.0\" \"pydantic>=2.10.6,<3.0.0\" \"tweepy[async]>=4.15.0,<5.0.0\" \"kafka-python>=2.0.5,<3.0.0\" \"loguru>=0.7.3,<1.0.0\" \"pyspark>=3.5.5,<4.0.0\" \"ruff>=0.9.9,<1.0.0\" \"transformers>=4.50.0,<5.0.0\" \"nltk>=3.9.1,<4.0.0\" \"emoji>=2.14.1,<3.0.0\" \"cassandra-driver>=3.29.2,<4.0.0\" \"polygon-api-client>=1.14.4,<2.0.0\" \"praw>=7.8.1,<8.0.0\" \"python-dotenv>=1.1.0,<2.0.0\" \"vadersentiment>=3.3.2\" \"typer>=0.15.2\" \"pendulum>=3.0.0\" \"confluent-kafka>=2.9.0\" pymongo pandas matplotlib &&
        echo 'Spark development environment ready!' &&
        echo 'Run your Reddit Sentiment script manually with:' &&
        echo '/opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.mongodb.spark:mongo-spark-connector_2.12:10.4.1 /opt/bitnami/spark/src/data_processing/main.py process-reddit' &&
        tail -f /dev/null
      "


  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda
    networks:
      - kafka-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongodb_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb_password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks:
      - kafka-network
    depends_on:
      - mongodb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - kafka-network
    depends_on:
      - mongodb
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 30s
      retries: 5

  # Add this new service
  streamlit:
    image: python:3.9-slim
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=mongodb_user
      - MONGODB_PASSWORD=mongodb_password
    networks:
      - kafka-network
    depends_on:
      - mongodb
    command: >
      bash -c "
        apt-get update && apt-get install -y --no-install-recommends git &&
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir streamlit plotly pandas pymongo pyyaml loguru &&
        cd /app &&
        streamlit run src/visualization/streamlit_dashboard.py -- /app/config/spark/reddit_sentiment_config.yaml
      "

volumes:
  redpanda-data:
  spark-volume:
  mongodb-data:
  grafana-data:

networks:
  kafka-network:
    driver: bridge