services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 2
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9093
      - --memory 4G
    ports:
      - "9093:9093"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda
    networks:
      - kafka-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./config/mongodb:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb_user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_password
      - MONGO_INITDB_DATABASE=social_media
    networks:
      - kafka-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 15s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - kafka-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  spark:
    image: bitnami/spark:latest
    ports:
      - "8090:8080"  # Spark UI
      - "7077:7077"  # Spark master port
      - "4040:4040"  # Application UI
    volumes:
      - ./src:/opt/bitnami/spark/src
      - ./config:/opt/bitnami/spark/config
      - ./scripts:/opt/bitnami/spark/scripts
      - ./logs/spark:/opt/bitnami/spark/logs
      - ./models:/opt/bitnami/spark/models
      - spark-volume:/bitnami
      - spark-cache:/root/.cache
    environment:
      - SPARK_MODE=master
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOME=/root
      - TRANSFORMERS_CACHE=/root/.cache
    networks:
      - kafka-network
    depends_on:
      - redpanda
      - mongodb
      - redis
    user: root  # Ensure we're running as root
    command: >
      bash -c "
        echo 'Setting up development environment...' &&
        mkdir -p /root/.local && chmod -R 777 /root/.local &&
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir \"yfinance>=0.2.54,<1.0.0\" \"pydantic>=2.10.6,<3.0.0\" \"tweepy[async]>=4.15.0,<5.0.0\" \"kafka-python>=2.0.5,<3.0.0\" \"loguru>=0.7.3,<1.0.0\" \"pyspark>=3.5.5,<4.0.0\" \"ruff>=0.9.9,<1.0.0\" \"transformers>=4.50.0,<5.0.0\" \"nltk>=3.9.1,<4.0.0\" \"emoji>=2.14.1,<3.0.0\" \"cassandra-driver>=3.29.2,<4.0.0\" \"polygon-api-client>=1.14.4,<2.0.0\" \"praw>=7.8.1,<8.0.0\" \"python-dotenv>=1.1.0,<2.0.0\" \"vadersentiment>=3.3.2\" \"typer>=0.15.2\" \"pendulum>=3.0.0\" \"confluent-kafka>=2.9.0\" \"redis>=5.0.0\" pymongo pandas matplotlib torch numpy scipy &&
        echo 'Installing additional sentiment analysis dependencies...' &&
        mkdir -p /opt/bitnami/spark/models &&
        python -c \"from transformers import AutoModelForSequenceClassification, AutoTokenizer; AutoModelForSequenceClassification.from_pretrained('ProsusAI/finbert'); AutoTokenizer.from_pretrained('ProsusAI/finbert')\" &&
        echo 'Spark development environment ready!' &&
        echo 'Run your Reddit Sentiment script manually with:' &&
        echo '/opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.mongodb.spark:mongo-spark-connector_2.12:10.4.1 /opt/bitnami/spark/src/data_processing/main.py process-reddit' &&
        tail -f /dev/null
      "
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  streamlit:
    image: python:3.9-slim
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./logs/streamlit:/app/logs
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - kafka-network
    depends_on:
      - mongodb
      - redis
    command: >
      bash -c "
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir streamlit pandas plotly pymongo pyyaml loguru redis &&
        cd /app &&
        streamlit run src/visualization/streamlit_dashboard.py -- /app/config/spark/reddit_sentiment_config.yaml
      "

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - kafka-network
    depends_on:
      - redis

volumes:
  redpanda-data:
  spark-volume:
  mongodb-data:
  redis-data:
  grafana-data:
  spark-cache:

networks:
  kafka-network:
    driver: bridge