services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 2
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9093
      - --memory 4G
    ports:
      - "9093:9093"
      - "29092:29092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=market_data_cluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=datacenter1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    networks:
      - kafka-network
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  cassandra-init:
    image: cassandra:latest
    volumes:
      - ./config/cassandra:/config/cassandra
    command: >
      bash -c "
        echo 'Waiting for Cassandra to start...' &&
        until cqlsh cassandra -e 'describe keyspaces'; do
          echo 'Cassandra not ready yet - retrying...';
          sleep 5;
        done &&
        echo 'Initializing Cassandra schema from schema.cql...' &&
        cqlsh cassandra -f /config/cassandra/schema.cql &&
        echo 'Schema initialization complete!'
      "
    networks:
      - kafka-network
    depends_on:
      cassandra:
        condition: service_healthy

  # Single Spark dev container with all components
  spark:
    image: bitnami/spark:latest
    ports:
      - "8090:8080"  # Spark UI
      - "7077:7077"  # Spark master port
      - "4040:4040"  # Application UI
    volumes:
      - ./src:/opt/bitnami/spark/src
      - ./config:/opt/bitnami/spark/config
      - ./scripts:/opt/bitnami/spark/scripts
      - spark-volume:/bitnami
    environment:
      - SPARK_MODE=master
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    networks:
      - kafka-network
    depends_on:
      - redpanda
      - cassandra
      - cassandra-init
    command: >
      bash -c "
        echo 'Setting up development environment...' &&
        pip install --no-cache-dir --upgrade pip &&
        pip install --no-cache-dir pyspark kafka-python cassandra-driver pandas matplotlib jupyter yfinance vaderSentiment PyYAML loguru pydantic &&
        mkdir -p /tmp/checkpoints && chmod 777 /tmp/checkpoints &&
        mkdir -p /opt/bitnami/spark/logs && chmod 777 /opt/bitnami/spark/logs &&
        echo 'Spark development environment ready!' &&
        echo 'Run your Reddit Sentiment script manually with:' &&
        echo '/opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,com.datastax.spark:spark-cassandra-connector_2.12:3.4.1 /opt/bitnami/spark/src/data_processing/reddit_sentiment_analyzer.py' &&
        tail -f /dev/null
      "


  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda
    networks:
      - kafka-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=hadesarchitect-cassandra-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - kafka-network
    depends_on:
      - cassandra
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  redpanda-data:
  spark-volume:
  cassandra-data:
  grafana-data:

networks:
  kafka-network:
    driver: bridge