# Kafka Broker Configuration
kafka:
  bootstrap_servers_dev: ["localhost:9093"]
  bootstrap_servers_prod: ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]

  topics:
    # Existing market data topics
    market_data_raw: "market-data-raw"
    market_data_validated: "market-data-validated"
    market_data_error: "market-data-error"

    # Reddit social media topics
    social_media_reddit_raw: "social-media-reddit-raw"
    social_media_reddit_validated: "social-media-reddit-validated"
    social_media_reddit_error: "social-media-reddit-error"
    social_media_reddit_invalid: "social-media-reddit-invalid"

    # Additional Reddit topics referenced in the collector code
    social_media_reddit_comments: "social-media-reddit-comments"
    social_media_reddit_comments_validated: "social-media-reddit-comments-validated"
    social_media_reddit_symbols: "social-media-reddit-symbols"
    social_media_reddit_symbols_validated: "social-media-reddit-symbols-validated"
    social_media_reddit_rising_historical: "social-media-reddit-rising-historical"

    # Combined sentiment topic (for processed sentiment data)
    sentiment_aggregated: "sentiment-aggregated"

  # Kafka consumer group IDs
  consumer_groups:
    market_data_validation: "market-data-validation-group"
    reddit_validation: "reddit-validation-group"
    reddit_comments_validation: "reddit-comments-validation-group"
    reddit_symbols_validation: "reddit-symbols-validation-group"

  # Kafka configuration parameters
  config:
    retention_ms: 604800000  # 7 days retention
    cleanup_policy: "delete"
    compression_type: "snappy"
    partitions: 8
    replication_factor: 3

  # Producer configuration
  producer:
    acks: "all"
    retries: 3
    batch_size: 16384
    linger_ms: 5
    buffer_memory: 33554432
    key_serializer: "org.apache.kafka.common.serialization.StringSerializer"
    value_serializer: "org.apache.kafka.common.serialization.StringSerializer"

  # Consumer configuration
  consumer:
    group_id: "market-pulse-ai"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    auto_commit_interval_ms: 5000
    key_deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    value_deserializer: "org.apache.kafka.common.serialization.StringDeserializer"

  # Kafka Connect configuration
  connect:
    rest_port: 8083
    config_storage_topic: "connect-configs"
    offset_storage_topic: "connect-offsets"
    status_storage_topic: "connect-status"
    config_storage_replication_factor: 1
    offset_storage_replication_factor: 1
    status_storage_replication_factor: 1