# NewsAPI Configuration for MarketPulseAI

# API Settings
api:
  key: "${NEWSAPI_KEY}"  # Environment variable - DO NOT hardcode
  base_url: "https://newsapi.org/v2"

# Collection Settings
collection:
  # How often to run collection (in minutes)
  frequency: 60
  max_requests_per_day: 10  # Maximum requests allowed per day

  # Max articles to fetch per query
  page_size: 100
  
  # Days of news to fetch (1-30)
  days_to_fetch: 7
  
  # Wait between API requests (in seconds)
  request_cooldown: 10
  
  # Persistence directory for processed IDs
  persistence_dir: "data/news/persistence"

# Content Filters
filters:
  # Search queries to use
  queries:
    - "stock market"
    - "financial news"
    - "stock price"
    - "market analysis"
    - "investment"
    - "earnings"
    - "Wall Street"
    - "NASDAQ"
    - "NYSE"
    - "S&P 500"
    - "Dow Jones"
  
  # News sources to include (optional)
  # If empty, all sources are included
  sources:
    - "bloomberg"
    - "financial-times"
    - "the-wall-street-journal"
    - "business-insider"
    - "cnbc"
    - "reuters"
    - "forbes"
  
  # News categories
  categories:
    - "business"
    - "finance"
  
  # Languages to include
  languages:
    - "en"
  
  # Countries to include (optional)
  countries:
    - "us"
    - "gb"

# Validation Settings
validation:
  min_title_length: 10
  min_content_length: 50