# config/spark/reddit_sentiment_config.yaml
app_name: "RedditSentimentAnalysis"
log_level: "INFO"

# Spark settings
spark_settings:
  processing_window_duration: "5 minutes"
  watermark_delay_threshold: "10 minutes"
  checkpoint_location_base_path: "/opt/bitnami/spark/checkpoints/reddit"

# Reference to Kafka config
kafka_config_path: "/opt/bitnami/spark/config/kafka/kafka_config.yaml"

# Redis configuration for sentiment processing
redis:
  host: redis
  port: 6379
  db: 0
  password: null
  socket_timeout: 5
  ttl:
    sentiment_data: 3600   # 1 hour in seconds
    time_series: 86400     # 24 hours in seconds
    stats: 86400           # 24 hours in seconds

# MongoDB configuration
mongodb:
  connection_host: mongodb
  connection_port: 27017
  auth_username: mongodb_user
  auth_password: mongodb_password
  database: social_media
  collection: reddit_sentiment

# Sentiment analysis configuration
sentiment_analysis:
  model: vader  # Options: vader, finbert, ensemble
  preprocessing:
    lowercase: true
    remove_urls: true
    remove_special_chars: true

# Processing configuration
processing:
  batch_interval_seconds: 60
  checkpoint_location: /tmp/reddit_checkpoint

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Spark Package Versions
spark_mongodb_package: "org.mongodb.spark:mongo-spark-connector_2.12:10.4.1"
spark_kafka_package: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1"