# config/spark/reddit_sentiment_config.yaml
app_name: "RedditSentimentAnalysis"
log_level: "INFO"

# Spark settings
spark_settings:
  processing_window_duration: "5 minutes"
  watermark_delay_threshold: "10 minutes"
  checkpoint_location_base_path: "/opt/bitnami/spark/checkpoints/reddit"

# Reference to Kafka config
kafka_config_path: "/opt/bitnami/spark/config/kafka/kafka_config.yaml"

# Cassandra configuration
cassandra:
  keyspace: "social_media"
  table: "reddit_sentiment"
  connection_host: "cassandra"
  connection_port: "9042"
  auth_username: "cassandra"
  auth_password: "cassandra"

  # --- Optional Settings ---

  # Spark Package Versions (Uncomment and adjust if you want to control versions via config)
  # spark_cassandra_package: "com.datastax.spark:spark-cassandra-connector_2.12:3.4.1"
  # spark_kafka_package: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1"

  # Cassandra Write Consistenc
  cassandra_write_consistency: "ANY" # Options: ANY, ONE, TWO, THREE, QUORUM, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE, ALL