# config/spark/reddit_sentiment_config.yaml
app_name: "RedditSentimentAnalysis"
log_level: "INFO"

# Spark settings
spark_settings:
  processing_window_duration: "5 minutes"
  watermark_delay_threshold: "10 minutes"
  checkpoint_location_base_path: "/opt/bitnami/spark/checkpoints/reddit"

# Reference to Kafka config
kafka_config_path: "/opt/bitnami/spark/config/kafka/kafka_config.yaml"

# MongoDB configuration
mongodb:
  database: "social_media"
  collection: "reddit_sentiment"
  connection_host: "mongodb"
  connection_port: "27017"
  auth_username: "mongodb_user"
  auth_password: "mongodb_password"
  
  # MongoDB write concern (w: "majority", j: true ensures data is written to disk)
  write_concern: "majority"
  
  # Optional settings
  connection_options:
    replicaSet: "rs0"
    maxPoolSize: 100
    connectTimeoutMS: 10000
    socketTimeoutMS: 10000

# Spark Package Versions
spark_mongodb_package: "org.mongodb.spark:mongo-spark-connector_2.12:10.4.1"
spark_kafka_package: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1"