# Configuration for the Spark Reddit Sentiment Analysis Pipeline

# Reference to Kafka config file (no need to duplicate Kafka config)
kafka_config_path: "../kafka/kafka_config.yaml"

# Cassandra Configuration
cassandra:
  keyspace: "marketpulse"
  table: "reddit_sentiment_aggregate"
  connection_host: "cassandra"

# Spark Application Settings
spark_settings:
  app_name: "RedditSentimentAnalysis"
  log_level: "INFO"

  # Spark Streaming Settings
  processing_window_duration: "1 minute"
  watermark_delay_threshold: "3 minutes"

  # Checkpointing Configuration
  checkpoint_location_base_path: "/opt/bitnami/spark/checkpoints/reddit_sentiment"

  # --- Optional Settings ---

  # Spark Package Versions (Uncomment and adjust if you want to control versions via config)
  # spark_cassandra_package: "com.datastax.spark:spark-cassandra-connector_2.12:3.4.1"
  # spark_kafka_package: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1"

  # Cassandra Write Consistenc
  cassandra_write_consistency: "ANY" # Options: ANY, ONE, TWO, THREE, QUORUM, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE, ALL