# config/spark/stock_processor_config.yaml
app_name: "StockDataProcessing"
log_level: "INFO"

# Spark settings
spark_settings:
  processing_window_duration: "5 minutes"
  watermark_delay_threshold: "10 minutes"
  checkpoint_location_base_path: "/opt/bitnami/spark/checkpoints/stock"

# Reference to Kafka config
kafka_config_path: "/opt/bitnami/spark/config/kafka/kafka_config.yaml"

# Cassandra configuration
cassandra:
  keyspace: "market_data"
  table: "stock_features"
  connection_host: "cassandra"
  connection_port: "9042"
  auth_username: "cassandra"
  auth_password: "cassandra"